apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hans-wehr-api.fullname" . }}
  labels:
    {{- include "hans-wehr-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hans-wehr-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hans-wehr-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hans-wehr-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: https
              containerPort: 443
          env:
            {{- if .Values.local }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "hans-wehr-api.fullname" . }}-env-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "hans-wehr-api.fullname" . }}-env-secret
                  key: DB_PASSWORD
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "hans-wehr-api.fullname" . }}-env-secret
                  key: EMAIL_USERNAME
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "hans-wehr-api.fullname" . }}-env-secret
                  key: EMAIL_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "hans-wehr-api.fullname" . }}-env-secret
                  key: JWT_SECRET_KEY
            {{- else }}
            - name: DB_USERNAME
              value: {{ .Values.env.DB_USERNAME }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD }}
            - name: EMAIL_USERNAME
              value: {{ .Values.env.EMAIL_USERNAME }}
            - name: EMAIL_PASSWORD
              value: {{ .Values.env.EMAIL_PASSWORD }}
            - name: JWT_SECRET_KEY
              value: {{ .Values.env.JWT_SECRET_KEY }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
